failsafe_manager_node:
  ros__parameters:
    status_topic: fcu_link/status
    input_target_topic: target_point
    output_target_topic: target_point_safe
    input_timeout_sec: 0.4
    output_rate_hz: 20.0
    safe_frame_id: delta_base_link
    safe_x: 0.0
    safe_y: 0.0
    safe_z: 0.25
