flight_commander_node:
  ros__parameters:
    service_topic: flight_command
    fcu_state_topic: fcu_state
    cmd_vel_topic: cmd_vel
    mavros_arm_topic: /mavros/cmd/arming
    mavros_set_mode_topic: /mavros/set_mode
    mavros_vel_topic: /mavros/setpoint_velocity/cmd_vel
    mavros_takeoff_topic: /mavros/cmd/takeoff
    vel_forward_rate_hz: 20.0
    use_mock: false
    max_vel_xy: 1.0
    max_vel_z: 0.5
