mock_mavros_pose_node:
  ros__parameters:
    topic_name: /mavros/local_position/pose
    frame_id: map
    trajectory_mode: circle   # hover | circle | line
    publish_rate_hz: 30.0
    origin_x: 0.0
    origin_y: 0.0
    origin_z: 1.2
    amplitude_x: 0.6
    amplitude_y: 0.6
    amplitude_z: 0.1
    circle_period_sec: 12.0
    line_period_sec: 8.0
    yaw_rate_rad_s: 0.2
